#pragma once

#include "D3DHeaders.h"

//D3D10_PRIMITIVE_TOPOLOGY
enum class D3DPrimitiveTopology : int {
	Undefined = D3D10_PRIMITIVE_TOPOLOGY_UNDEFINED,
	PointList = D3D10_PRIMITIVE_TOPOLOGY_POINTLIST,
	LineList = D3D10_PRIMITIVE_TOPOLOGY_LINELIST,
	LineStrip = D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP,
	TriangleList = D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST,
	TriangleStrip = D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP,
	LineListAdj = D3D10_PRIMITIVE_TOPOLOGY_LINELIST_ADJ,
	LineStripAdj = D3D10_PRIMITIVE_TOPOLOGY_LINESTRIP_ADJ,
	TriangleListAdj = D3D10_PRIMITIVE_TOPOLOGY_TRIANGLELIST_ADJ,
	TriangleStripAdj = D3D10_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP_ADJ,
};